"""create sweets table

Revision ID: a00fd88dbde5
Revises: 2c06da3411e9
Create Date: 2025-12-13 17:46:03.193898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00fd88dbde5'
down_revision: Union[str, Sequence[str], None] = '2c06da3411e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sweets_category'), 'sweets', ['category'], unique=False)
    op.create_index(op.f('ix_sweets_id'), 'sweets', ['id'], unique=False)
    op.create_index(op.f('ix_sweets_name'), 'sweets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sweets_name'), table_name='sweets')
    op.drop_index(op.f('ix_sweets_id'), table_name='sweets')
    op.drop_index(op.f('ix_sweets_category'), table_name='sweets')
    op.drop_table('sweets')
    # ### end Alembic commands ###
